version: '3.5'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  db-data:
    driver: local

services:
  app:
    image: golang:1.12
    container_name: app
    ports:
      - 8000:8000
    volumes:
      - .:/go
    working_dir: /go/src/api
    entrypoint: "go run main.go"
    networks:
      - frontend
      - backend
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=develop
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/local/mysql/etc-mysql.cnf:/etc/mysql/conf.d/etc-mysql.cnf
      - db-data:/var/lib/mysql
    networks:
      - backend

